AWSTemplateFormatVersion: 2010-09-09
Description: |
  Cloudformation template for Phonebook Application

Resources:
  WebserverSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: Enable HTTP
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  WebserverHost:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: ami-02354e95b39ca8dec
      InstanceId: t2.micro
      KeyName: aws-key
      SecurityGroupIds:
        - !Ref WebserverSecurityGroup
      Tags:
        - Key: Name
          Value: !Sub Web Server of ${AWS::StackName} StackName
      UserData: 
        Fn::Base64:
          !Sub
            - | 
              #! /bin/bash
              yum update -y
              yum install python3 -y
              pip3 install flask
              pip3 install flask_mysql
              echo "${MyDBURI}" > /home/ec2-user/dbserver.endpoint
              FOLDER="https://raw.githubusercontent.com/mucahit-k/aws-projects/master/projects/004-phonebook-web-application/"
              curl -s --create-dirs -o "/home/ec2-user/templates/index.html" -L "$FOLDER"templates/index.html
              curl -s --create-dirs -o "/home/ec2-user/templates/add-update.html" -L "$FOLDER"templates/add-update.html
              curl -s --create-dirs -o "/home/ec2-user/templates/delete.html" -L "$FOLDER"templates/delete.html
              curl -s --create-dirs -o "/home/ec2-user/app.py" -L "$FOLDER"app.py
              python3 /home/ec2-user/app.py
            - MyDBURI: !GetAtt MyDatabaseServer.Endpoint.Address

  MyDbSecurityGroup:
    Type: "AWS::RDS::DBSecurityGroup"
    Properties:
      DBSecurityGroupIngress:
        - EC2SecurityGroupId: !Ref WebserverSecurityGroup
        - CidrIp: 0.0.0.0/0
      GroupDescription: Frontend Access

MyDatabaseServer:
  Type: "AWS::RDS::DBInstance"
  Properties:
    AllocatedStorage: 20
    AllowMajorVersionUpgrade: false
    AutoMinorVersionUpgrade: true
    BackupRetentionPeriod: 0
    DBInstanceClass: db.t2.micro #required
    DBInstanceIdentifier: phonebook-db-server
    DBName: phonebook
    DBSecurityGroups:
      - !Ref MyDbSecurityGroup
    DeletionProtection: false
    Engine: MySQL
    EngineVersion: 8.0.19
    MasterUserPassword: Clarusway-123
    MasterUsername: admin
    MonitoringInterval: 0
    MultiAZ: false
    Port: 3306
    PubliclyAccessible: true


Outputs:
  WebsiteURL:
    Description: Phonebook APP URL
    Value: !Sub 
      - http://${PublicAddress}
      - PublicAddress: !GetAtt WebserverHost.PublicDnsName